name: Deploy using Pulumi
on:
  push:
    branches:
      - main
jobs:
  deploy-beta:
    name: Deploy to beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.BETA_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.BETA_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.BETA_AWS_SECRET_ACCESS_KEY }}
      - run: npm ci
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: beta
          diff: true
          upsert: true
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          STAGE: beta

  deploy-prod:
    name: Deploy to prod
    needs: deploy-beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      - run: npm ci
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          diff: true
          upsert: true
          refresh: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          STAGE: prod
